swagger: "2.0"
info:
  title: Ecommerce Project
  description: This is my Wakeupcoders Ecommerce Project API Documentation
  version: 1.0
  contact:
    email: wakeupcoders@gmail.com
  liscence:
    name: Apache 2.0
    url: "http://www.apache.org/liscences/LIS"
  servers:
    -url: http://localhost:5000
    description: THis is my local Server
    -url: http://example.com/
    description: This is my original URL
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
schemes:
- "https"
- "http"


definitions:
  User:
    properties:
      id:
        type: integer
      name:
        type: string
    # Both properties are required
    required:  
      - id
      - name

#Return Users From get request
paths:
# Admin Module Documentation
  /api/products:
    post:
      tags:
      - "Products Module"
      summary: Creates a new user.
      parameters:
        - in: body
          name: user
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: OK
    get:
      tags:
      - "Products Module"
      summary: "Add a new pet to the store"
      description: ""
      operationId: "addPet"
      summary: Returns a string.
      description: String Chechup
      security:
        - Bearer: []
      responses:
        200:    # status code
          description: Successul Response
          schema: 
            type: string
            example: "Users String"
        400:
          description: User Error
          schema: 
            type: string
            example: "Some Error "      
  /api/products/{petId}:
    get:
      tags:
      - "Products Module"
      summary: "Find pet by ID"
      description: "Returns a single pet"
      operationId: "getPetById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "petId"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Pet"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
    delete:
      tags:
      - "Products Module"
      summary: "Add a new pet to the store"
      description: ""
      operationId: "addPet"
      summary: Returns a string.
      description: String Chechup
      security:
        - Bearer: []
      responses:
        200:    # status code
          description: Successul Response
          schema: 
            type: string
            example: "Users String"
        400:
          description: User Error
          schema: 
            type: string
            example: "Some Error "
    put:
      tags:
      - "Products Module"
      summary: "Update an existing pet"
      description: ""
      operationId: "updatePet"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Pet"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
        "405":
          description: "Validation exception"

# User Module Documentation
  /api/register:
    post:
      tags:
      - "User Module"
      summary: Creates a new user.
      parameters:
        - in: body
          name: user
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: OK
    get:
      tags:
      - "User Module"
      summary: "Add a new pet to the store"
      description: ""
      operationId: "addPet"
      summary: Returns a string.
      description: String Chechup
      security:
        - Bearer: []
      responses:
        200:    # status code
          description: Successul Response
          schema: 
            type: string
            example: "Users String"
        400:
          description: User Error
          schema: 
            type: string
            example: "Some Error "
  
